### PR TITLE
Conda recipe

### PR DESCRIPTION
**Pull request by sdrobert**
Hello,

This PR adds a conda recipe in the "conda-recipe" folder. In addition, a GitHub workflow was added to simplify the build process on release.

The construction is similar to the recipe for [tdev2](https://github.com/zerospeech/tdev2/pull/1#issue-1586839316). The recipe will need to be updated with new versions of the package. Because the codebase builds C extensions, multiple versions of the same package exist for different versions of python (3.8, 3.9, and 3.10) as well as OSs (Linux, macOS, Windows). The various combinations are uploaded as artifacts [here](https://github.com/sdrobert/libri-light-abx2/actions/runs/4197379079). I've also uploaded them to my own conda channel, "sdrobert". To test them, try

``` sh
conda install -c conda-forge -c pytorch -c sdrobert zerospeech-libriabx2 pytorch::pytorch
```

Note that the pytorch channel's version of pytorch is currently necessary because of torchaudio. torchaudio does not play nicely with the conda-forge version of pytorch. If pytorch is already installed from that channel, you can remove the "pytorch::pytorch" part from above.

Let me know if this works!

Sean

### CODE REVIEW

**Comment by nhamilakis** [comment]
Hello, thank you very much for your work on this. I have a question before i merge this. Is it possible to automaticly upload artifacts to anaconda in the workflow ? i can set up a `$CONDA_USER` `$CONDA_PWD` on the secrets section of the repo if needed. We already have our anaconda channel [CoML anaconda](https://anaconda.org/CoML)

**Comment by sdrobert** [comment]
Hey Nick,

You're welcome. Hope I'm not too irritating with all these PRs.

It's definitely possible, and yeah, there are a few of those actions around. It might work as-is, though it builds on linux and uses "conda convert" to convert to other OSes. Not sure how well that works - haven't used that functionality. Let me see if it's as easy as just installing the client and uploading in a new step.

**Comment by nhamilakis** [comment]
Don't worry about it, you are helping with the packaging it's perfectly normal that it requires multiple PRs.
If you could modify the action to do that, it would be very helpful for maintaining &  keeping the package up to date in the future.
If it doesn't work, don't worry too much about it. I can look for another solution, or do it manually (although i would like to avoid that).

Tell when you are done so i can merge all your PRs

**Comment by sdrobert** [comment]
Ok, it looks like it's working.

I've replaced the block uploading to github with one uploading to anaconda. The block is the same for all the PRs. Here's it working on my [tdev2 PR](https://github.com/sdrobert/tdev2/actions/runs/4237855141). In order for it to work for you, you'll need to configure two [variables](https://docs.github.com/en/actions/learn-github-actions/variables).

1. A secret, called `ANACONDA_TOKEN`, which stores an authentication token with write access to your anaconda channel. I created mine using `anaconda-client` and the command `anaconda auth --create -n name-of-key --scope "api:write"`.
2. A repository variable, called `ANACONDA_USERNAME` which is the username/channel of your repo.

Best,
Sean

**Pull request merged**
